# Generated by Django 2.0.4 on 2018-04-19 22:45

from django.db import migrations, models
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180418_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='icon',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=250, verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='news',
            name='annonce',
            field=tinymce.models.HTMLField(verbose_name='Анонс новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Повний текст новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=256, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Заголовок'),
        ),
    ]
