# Generated by Django 2.0.4 on 2018-04-19 22:48

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180419_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='icon',
            field=filebrowser.fields.FileBrowseField(max_length=250, null=True, verbose_name='Зображення'),
        ),
    ]
