# Generated by Django 2.0.4 on 2018-04-30 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('saint', models.CharField(max_length=255, verbose_name='На честь святого')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('city', models.CharField(max_length=255, verbose_name='Місто')),
                ('body', tinymce.models.HTMLField(verbose_name='Опис')),
                ('abbot', models.CharField(max_length=255, verbose_name='Настоятель')),
                ('link', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Посилання')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('icon', filebrowser.fields.FileBrowseField(max_length=250, null=True, verbose_name='Зображення')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=20, verbose_name='Телефон')),
                ('phonename', models.CharField(max_length=50, verbose_name='Примитки')),
                ('tample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tamples.Tample')),
            ],
        ),
    ]
