# Generated by Django 2.0.4 on 2018-04-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamples', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplePhone',
            new_name='TamplePhone',
        ),
    ]
