# Generated by Django 2.0.4 on 2018-04-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamples', '0002_auto_20180430_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamplephone',
            name='phonename',
            field=models.CharField(max_length=50, null=True, verbose_name='Примитки'),
        ),
    ]
