# Generated by Django 2.0.4 on 2018-04-30 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tamples', '0003_auto_20180430_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tample',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tample',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
